
// This file has been generated by the GUI designer. Do not modify.
namespace Revanche.Views.Fields
{
	public partial class Decimal
	{
		private global::Gtk.SpinButton spinbutton;

		protected virtual void Build ()
		{
			global::Stetic.Gui.Initialize (this);
			// Widget Revanche.Views.Fields.Decimal
			global::Stetic.BinContainer.Attach (this);
			this.Name = "Revanche.Views.Fields.Decimal";
			// Container child Revanche.Views.Fields.Decimal.Gtk.Container+ContainerChild
			this.spinbutton = new global::Gtk.SpinButton (-999, 999, 1);
			this.spinbutton.CanFocus = true;
			this.spinbutton.Name = "spinbutton";
			this.spinbutton.Adjustment.PageIncrement = 10;
			this.spinbutton.ClimbRate = 1;
			this.spinbutton.Digits = ((uint)(2));
			this.spinbutton.Numeric = true;
			this.Add (this.spinbutton);
			if ((this.Child != null)) {
				this.Child.ShowAll ();
			}
			this.Hide ();
			this.spinbutton.KeyPressEvent += new global::Gtk.KeyPressEventHandler (this.handlerKey);
		}
	}
}
