
// This file has been generated by the GUI designer. Do not modify.
namespace Revanche.Views.Displays
{
	public partial class Text
	{
		private global::Gtk.Label label;

		protected virtual void Build ()
		{
			global::Stetic.Gui.Initialize (this);
			// Widget Revanche.Views.Displays.Text
			global::Stetic.BinContainer.Attach (this);
			this.Name = "Revanche.Views.Displays.Text";
			// Container child Revanche.Views.Displays.Text.Gtk.Container+ContainerChild
			this.label = new global::Gtk.Label ();
			this.label.Name = "label";
			this.label.Xalign = 1F;
			this.label.LabelProp = global::Mono.Unix.Catalog.GetString ("label6");
			this.label.UseMarkup = true;
			this.label.Wrap = true;
			this.Add (this.label);
			if ((this.Child != null)) {
				this.Child.ShowAll ();
			}
			this.Hide ();
		}
	}
}
