
// This file has been generated by the GUI designer. Do not modify.
namespace Revanche.Views.Fields
{
	public partial class Toggle
	{
		private global::Gtk.ToggleButton togglebutton;

		protected virtual void Build ()
		{
			global::Stetic.Gui.Initialize (this);
			// Widget Revanche.Views.Fields.Toggle
			global::Stetic.BinContainer.Attach (this);
			this.Name = "Revanche.Views.Fields.Toggle";
			// Container child Revanche.Views.Fields.Toggle.Gtk.Container+ContainerChild
			this.togglebutton = new global::Gtk.ToggleButton ();
			this.togglebutton.CanFocus = true;
			this.togglebutton.Name = "togglebutton";
			this.togglebutton.UseUnderline = true;
			this.togglebutton.Label = global::Mono.Unix.Catalog.GetString ("GtkToggleButton");
			this.Add (this.togglebutton);
			if ((this.Child != null)) {
				this.Child.ShowAll ();
			}
			this.Hide ();
			this.togglebutton.Clicked += new global::System.EventHandler (this.handlerClicked);
			this.togglebutton.KeyPressEvent += new global::Gtk.KeyPressEventHandler (this.handlerKey);
		}
	}
}
