
// This file has been generated by the GUI designer. Do not modify.
namespace Revanche.Views.Fields
{
	public partial class Date
	{
		private global::Gtk.Button button18;
		private global::Gtk.HBox hbox2;
		private global::Gtk.HBox hbox1;
		private global::Gtk.Image image;
		private global::Gtk.Label label;

		protected virtual void Build ()
		{
			global::Stetic.Gui.Initialize (this);
			// Widget Revanche.Views.Fields.Date
			global::Stetic.BinContainer.Attach (this);
			this.Name = "Revanche.Views.Fields.Date";
			// Container child Revanche.Views.Fields.Date.Gtk.Container+ContainerChild
			this.button18 = new global::Gtk.Button ();
			this.button18.CanFocus = true;
			this.button18.Name = "button18";
			// Container child button18.Gtk.Container+ContainerChild
			this.hbox2 = new global::Gtk.HBox ();
			this.hbox2.Name = "hbox2";
			this.hbox2.Spacing = 6;
			// Container child hbox2.Gtk.Box+BoxChild
			this.hbox1 = new global::Gtk.HBox ();
			this.hbox1.Name = "hbox1";
			this.hbox1.Spacing = 6;
			// Container child hbox1.Gtk.Box+BoxChild
			this.image = new global::Gtk.Image ();
			this.image.Name = "image";
			this.image.Pixbuf = global::Stetic.IconLoader.LoadIcon (this, "stock_calendar", global::Gtk.IconSize.Menu);
			this.hbox1.Add (this.image);
			global::Gtk.Box.BoxChild w1 = ((global::Gtk.Box.BoxChild)(this.hbox1 [this.image]));
			w1.Position = 0;
			w1.Expand = false;
			w1.Fill = false;
			// Container child hbox1.Gtk.Box+BoxChild
			this.label = new global::Gtk.Label ();
			this.label.Name = "label";
			this.label.LabelProp = global::Mono.Unix.Catalog.GetString ("DateButton");
			this.hbox1.Add (this.label);
			global::Gtk.Box.BoxChild w2 = ((global::Gtk.Box.BoxChild)(this.hbox1 [this.label]));
			w2.Position = 1;
			w2.Expand = false;
			w2.Fill = false;
			this.hbox2.Add (this.hbox1);
			global::Gtk.Box.BoxChild w3 = ((global::Gtk.Box.BoxChild)(this.hbox2 [this.hbox1]));
			w3.Position = 0;
			w3.Fill = false;
			this.button18.Add (this.hbox2);
			this.button18.Label = null;
			this.Add (this.button18);
			if ((this.Child != null)) {
				this.Child.ShowAll ();
			}
			this.Hide ();
			this.button18.Clicked += new global::System.EventHandler (this.handlerClicked);
			this.button18.KeyPressEvent += new global::Gtk.KeyPressEventHandler (this.handlerKey);
		}
	}
}
