
// This file has been generated by the GUI designer. Do not modify.
namespace Revanche.Views.Objects
{
	public partial class Properties
	{
		private global::Gtk.Alignment alignment3;
		private global::Gtk.Table table1;

		protected virtual void Build ()
		{
			global::Stetic.Gui.Initialize (this);
			// Widget Revanche.Views.Objects.Properties
			global::Stetic.BinContainer.Attach (this);
			this.Name = "Revanche.Views.Objects.Properties";
			// Container child Revanche.Views.Objects.Properties.Gtk.Container+ContainerChild
			this.alignment3 = new global::Gtk.Alignment (0.5F, 0.5F, 1F, 1F);
			this.alignment3.Name = "alignment3";
			this.alignment3.LeftPadding = ((uint)(10));
			this.alignment3.RightPadding = ((uint)(10));
			// Container child alignment3.Gtk.Container+ContainerChild
			this.table1 = new global::Gtk.Table (((uint)(1)), ((uint)(2)), false);
			this.table1.Name = "table1";
			this.table1.ColumnSpacing = ((uint)(40));
			this.alignment3.Add (this.table1);
			this.Add (this.alignment3);
			if ((this.Child != null)) {
				this.Child.ShowAll ();
			}
			this.Hide ();
		}
	}
}
