
// This file has been generated by the GUI designer. Do not modify.
namespace Revanche.Views.Objects
{
	public partial class Identifiable
	{
		private global::Gtk.Alignment rootAlignment;
		private global::Gtk.Frame containerFrame;
		private global::Gtk.Alignment GtkAlignment;
		private global::Gtk.VBox vbox3;
		private global::Gtk.HBox toolbar;
		private global::Gtk.EventBox arrowEventBox;
		private global::Gtk.Arrow arrow;
		private global::Gtk.Label title;
		private global::Gtk.HBox actionButtons;
		private global::Gtk.Button viewButton;
		private global::Gtk.HBox hbox6;
		private global::Gtk.Image viewIcon;
		private global::Gtk.Label viewLabel;
		private global::Gtk.Button noteButton;
		private global::Gtk.HBox hbox4;
		private global::Gtk.Image notesIcon;
		private global::Gtk.Label notesLabel;
		private global::Gtk.Button editButton;
		private global::Gtk.HBox hbox5;
		private global::Gtk.Image editIcon;
		private global::Gtk.Label editLabel;
		private global::Gtk.HSeparator separator;
		private global::Gtk.Alignment alignment5;
		private global::Gtk.VBox dataContainer;
		private global::Gtk.Alignment alignment6;
		private global::Gtk.Label notes;
		private global::Revanche.Views.Objects.Properties properties;
		private global::Revanche.Views.Objects.Children children;
		private global::Revanche.Views.Objects.Collection collection;

		protected virtual void Build ()
		{
			global::Stetic.Gui.Initialize (this);
			// Widget Revanche.Views.Objects.Identifiable
			global::Stetic.BinContainer.Attach (this);
			this.Name = "Revanche.Views.Objects.Identifiable";
			// Container child Revanche.Views.Objects.Identifiable.Gtk.Container+ContainerChild
			this.rootAlignment = new global::Gtk.Alignment (0.5F, 0.5F, 1F, 1F);
			this.rootAlignment.Name = "rootAlignment";
			this.rootAlignment.BottomPadding = ((uint)(10));
			// Container child rootAlignment.Gtk.Container+ContainerChild
			this.containerFrame = new global::Gtk.Frame ();
			this.containerFrame.Name = "containerFrame";
			// Container child containerFrame.Gtk.Container+ContainerChild
			this.GtkAlignment = new global::Gtk.Alignment (0F, 0F, 1F, 1F);
			this.GtkAlignment.Name = "GtkAlignment";
			// Container child GtkAlignment.Gtk.Container+ContainerChild
			this.vbox3 = new global::Gtk.VBox ();
			this.vbox3.Name = "vbox3";
			// Container child vbox3.Gtk.Box+BoxChild
			this.toolbar = new global::Gtk.HBox ();
			this.toolbar.Name = "toolbar";
			this.toolbar.Spacing = 6;
			// Container child toolbar.Gtk.Box+BoxChild
			this.arrowEventBox = new global::Gtk.EventBox ();
			this.arrowEventBox.Name = "arrowEventBox";
			// Container child arrowEventBox.Gtk.Container+ContainerChild
			this.arrow = new global::Gtk.Arrow (((global::Gtk.ArrowType)(1)), ((global::Gtk.ShadowType)(2)));
			this.arrow.Name = "arrow";
			this.arrowEventBox.Add (this.arrow);
			this.toolbar.Add (this.arrowEventBox);
			global::Gtk.Box.BoxChild w2 = ((global::Gtk.Box.BoxChild)(this.toolbar [this.arrowEventBox]));
			w2.Position = 0;
			w2.Expand = false;
			w2.Fill = false;
			// Container child toolbar.Gtk.Box+BoxChild
			this.title = new global::Gtk.Label ();
			this.title.HeightRequest = 26;
			this.title.Name = "title";
			this.title.LabelProp = global::Mono.Unix.Catalog.GetString ("label2");
			this.title.UseMarkup = true;
			this.toolbar.Add (this.title);
			global::Gtk.Box.BoxChild w3 = ((global::Gtk.Box.BoxChild)(this.toolbar [this.title]));
			w3.Position = 1;
			w3.Expand = false;
			w3.Fill = false;
			// Container child toolbar.Gtk.Box+BoxChild
			this.actionButtons = new global::Gtk.HBox ();
			this.actionButtons.Name = "actionButtons";
			this.actionButtons.Spacing = 6;
			// Container child actionButtons.Gtk.Box+BoxChild
			this.viewButton = new global::Gtk.Button ();
			this.viewButton.CanFocus = true;
			this.viewButton.Name = "viewButton";
			// Container child viewButton.Gtk.Container+ContainerChild
			this.hbox6 = new global::Gtk.HBox ();
			this.hbox6.Name = "hbox6";
			this.hbox6.Spacing = 6;
			// Container child hbox6.Gtk.Box+BoxChild
			this.viewIcon = new global::Gtk.Image ();
			this.viewIcon.Name = "viewIcon";
			this.viewIcon.Pixbuf = global::Stetic.IconLoader.LoadIcon (this, "gtk-find", global::Gtk.IconSize.Menu);
			this.hbox6.Add (this.viewIcon);
			global::Gtk.Box.BoxChild w4 = ((global::Gtk.Box.BoxChild)(this.hbox6 [this.viewIcon]));
			w4.Position = 0;
			w4.Expand = false;
			w4.Fill = false;
			// Container child hbox6.Gtk.Box+BoxChild
			this.viewLabel = new global::Gtk.Label ();
			this.viewLabel.Name = "viewLabel";
			this.viewLabel.LabelProp = global::Mono.Unix.Catalog.GetString ("View");
			this.hbox6.Add (this.viewLabel);
			global::Gtk.Box.BoxChild w5 = ((global::Gtk.Box.BoxChild)(this.hbox6 [this.viewLabel]));
			w5.Position = 1;
			w5.Expand = false;
			w5.Fill = false;
			this.viewButton.Add (this.hbox6);
			this.viewButton.Label = null;
			this.actionButtons.Add (this.viewButton);
			global::Gtk.Box.BoxChild w7 = ((global::Gtk.Box.BoxChild)(this.actionButtons [this.viewButton]));
			w7.Position = 0;
			w7.Expand = false;
			w7.Fill = false;
			// Container child actionButtons.Gtk.Box+BoxChild
			this.noteButton = new global::Gtk.Button ();
			this.noteButton.CanFocus = true;
			this.noteButton.Name = "noteButton";
			// Container child noteButton.Gtk.Container+ContainerChild
			this.hbox4 = new global::Gtk.HBox ();
			this.hbox4.Name = "hbox4";
			this.hbox4.Spacing = 6;
			// Container child hbox4.Gtk.Box+BoxChild
			this.notesIcon = new global::Gtk.Image ();
			this.notesIcon.Name = "notesIcon";
			this.notesIcon.Pixbuf = global::Stetic.IconLoader.LoadIcon (this, "gtk-dnd", global::Gtk.IconSize.Menu);
			this.hbox4.Add (this.notesIcon);
			global::Gtk.Box.BoxChild w8 = ((global::Gtk.Box.BoxChild)(this.hbox4 [this.notesIcon]));
			w8.Position = 0;
			w8.Expand = false;
			w8.Fill = false;
			// Container child hbox4.Gtk.Box+BoxChild
			this.notesLabel = new global::Gtk.Label ();
			this.notesLabel.Name = "notesLabel";
			this.notesLabel.LabelProp = global::Mono.Unix.Catalog.GetString ("Notes");
			this.hbox4.Add (this.notesLabel);
			global::Gtk.Box.BoxChild w9 = ((global::Gtk.Box.BoxChild)(this.hbox4 [this.notesLabel]));
			w9.Position = 1;
			w9.Expand = false;
			w9.Fill = false;
			this.noteButton.Add (this.hbox4);
			this.noteButton.Label = null;
			this.actionButtons.Add (this.noteButton);
			global::Gtk.Box.BoxChild w11 = ((global::Gtk.Box.BoxChild)(this.actionButtons [this.noteButton]));
			w11.Position = 1;
			w11.Expand = false;
			w11.Fill = false;
			// Container child actionButtons.Gtk.Box+BoxChild
			this.editButton = new global::Gtk.Button ();
			this.editButton.CanFocus = true;
			this.editButton.Name = "editButton";
			// Container child editButton.Gtk.Container+ContainerChild
			this.hbox5 = new global::Gtk.HBox ();
			this.hbox5.Name = "hbox5";
			this.hbox5.Spacing = 6;
			// Container child hbox5.Gtk.Box+BoxChild
			this.editIcon = new global::Gtk.Image ();
			this.editIcon.Name = "editIcon";
			this.editIcon.Pixbuf = global::Stetic.IconLoader.LoadIcon (this, "gtk-edit", global::Gtk.IconSize.Menu);
			this.hbox5.Add (this.editIcon);
			global::Gtk.Box.BoxChild w12 = ((global::Gtk.Box.BoxChild)(this.hbox5 [this.editIcon]));
			w12.Position = 0;
			w12.Expand = false;
			w12.Fill = false;
			// Container child hbox5.Gtk.Box+BoxChild
			this.editLabel = new global::Gtk.Label ();
			this.editLabel.Name = "editLabel";
			this.editLabel.LabelProp = global::Mono.Unix.Catalog.GetString ("Edit");
			this.hbox5.Add (this.editLabel);
			global::Gtk.Box.BoxChild w13 = ((global::Gtk.Box.BoxChild)(this.hbox5 [this.editLabel]));
			w13.Position = 1;
			w13.Expand = false;
			w13.Fill = false;
			this.editButton.Add (this.hbox5);
			this.editButton.Label = null;
			this.actionButtons.Add (this.editButton);
			global::Gtk.Box.BoxChild w15 = ((global::Gtk.Box.BoxChild)(this.actionButtons [this.editButton]));
			w15.Position = 2;
			w15.Expand = false;
			w15.Fill = false;
			this.toolbar.Add (this.actionButtons);
			global::Gtk.Box.BoxChild w16 = ((global::Gtk.Box.BoxChild)(this.toolbar [this.actionButtons]));
			w16.PackType = ((global::Gtk.PackType)(1));
			w16.Position = 2;
			w16.Expand = false;
			w16.Fill = false;
			this.vbox3.Add (this.toolbar);
			global::Gtk.Box.BoxChild w17 = ((global::Gtk.Box.BoxChild)(this.vbox3 [this.toolbar]));
			w17.Position = 0;
			w17.Expand = false;
			w17.Fill = false;
			// Container child vbox3.Gtk.Box+BoxChild
			this.separator = new global::Gtk.HSeparator ();
			this.separator.Name = "separator";
			this.vbox3.Add (this.separator);
			global::Gtk.Box.BoxChild w18 = ((global::Gtk.Box.BoxChild)(this.vbox3 [this.separator]));
			w18.Position = 1;
			w18.Expand = false;
			w18.Fill = false;
			// Container child vbox3.Gtk.Box+BoxChild
			this.alignment5 = new global::Gtk.Alignment (0.5F, 0.5F, 1F, 1F);
			this.alignment5.Name = "alignment5";
			// Container child alignment5.Gtk.Container+ContainerChild
			this.dataContainer = new global::Gtk.VBox ();
			this.dataContainer.Name = "dataContainer";
			// Container child dataContainer.Gtk.Box+BoxChild
			this.alignment6 = new global::Gtk.Alignment (0.5F, 0.5F, 1F, 1F);
			this.alignment6.Name = "alignment6";
			this.alignment6.LeftPadding = ((uint)(10));
			this.alignment6.RightPadding = ((uint)(10));
			// Container child alignment6.Gtk.Container+ContainerChild
			this.notes = new global::Gtk.Label ();
			this.notes.Name = "notes";
			this.notes.LabelProp = global::Mono.Unix.Catalog.GetString ("notes");
			this.notes.UseMarkup = true;
			this.notes.Wrap = true;
			this.notes.Justify = ((global::Gtk.Justification)(3));
			this.alignment6.Add (this.notes);
			this.dataContainer.Add (this.alignment6);
			global::Gtk.Box.BoxChild w20 = ((global::Gtk.Box.BoxChild)(this.dataContainer [this.alignment6]));
			w20.Position = 0;
			w20.Expand = false;
			w20.Fill = false;
			// Container child dataContainer.Gtk.Box+BoxChild
			this.properties = new global::Revanche.Views.Objects.Properties ();
			this.properties.Events = ((global::Gdk.EventMask)(256));
			this.properties.Name = "properties";
			this.dataContainer.Add (this.properties);
			global::Gtk.Box.BoxChild w21 = ((global::Gtk.Box.BoxChild)(this.dataContainer [this.properties]));
			w21.Position = 1;
			w21.Expand = false;
			// Container child dataContainer.Gtk.Box+BoxChild
			this.children = new global::Revanche.Views.Objects.Children ();
			this.children.Events = ((global::Gdk.EventMask)(256));
			this.children.Name = "children";
			this.dataContainer.Add (this.children);
			global::Gtk.Box.BoxChild w22 = ((global::Gtk.Box.BoxChild)(this.dataContainer [this.children]));
			w22.Position = 2;
			w22.Expand = false;
			// Container child dataContainer.Gtk.Box+BoxChild
			this.collection = new global::Revanche.Views.Objects.Collection ();
			this.collection.Events = ((global::Gdk.EventMask)(256));
			this.collection.Name = "collection";
			this.dataContainer.Add (this.collection);
			global::Gtk.Box.BoxChild w23 = ((global::Gtk.Box.BoxChild)(this.dataContainer [this.collection]));
			w23.Position = 3;
			this.alignment5.Add (this.dataContainer);
			this.vbox3.Add (this.alignment5);
			global::Gtk.Box.BoxChild w25 = ((global::Gtk.Box.BoxChild)(this.vbox3 [this.alignment5]));
			w25.Position = 2;
			this.GtkAlignment.Add (this.vbox3);
			this.containerFrame.Add (this.GtkAlignment);
			this.rootAlignment.Add (this.containerFrame);
			this.Add (this.rootAlignment);
			if ((this.Child != null)) {
				this.Child.ShowAll ();
			}
			this.Hide ();
			this.arrowEventBox.ButtonReleaseEvent += new global::Gtk.ButtonReleaseEventHandler (this.handlerArrowToggle);
			this.viewButton.Clicked += new global::System.EventHandler (this.handlerView);
			this.noteButton.Clicked += new global::System.EventHandler (this.handlerNotes);
			this.editButton.Clicked += new global::System.EventHandler (this.handlerEdit);
		}
	}
}
