
// This file has been generated by the GUI designer. Do not modify.
namespace Revanche.Views.Objects
{
	public partial class Collection
	{
		private global::Gtk.Alignment alignment2;
		private global::Gtk.VBox outerBox;
		private global::Gtk.VBox vbox;

		protected virtual void Build ()
		{
			global::Stetic.Gui.Initialize (this);
			// Widget Revanche.Views.Objects.Collection
			global::Stetic.BinContainer.Attach (this);
			this.Name = "Revanche.Views.Objects.Collection";
			// Container child Revanche.Views.Objects.Collection.Gtk.Container+ContainerChild
			this.alignment2 = new global::Gtk.Alignment (0.5F, 0.5F, 1F, 1F);
			this.alignment2.Name = "alignment2";
			// Container child alignment2.Gtk.Container+ContainerChild
			this.outerBox = new global::Gtk.VBox ();
			this.outerBox.Name = "outerBox";
			this.outerBox.Spacing = 6;
			// Container child outerBox.Gtk.Box+BoxChild
			this.vbox = new global::Gtk.VBox ();
			this.vbox.Name = "vbox";
			this.vbox.Spacing = 10;
			this.outerBox.Add (this.vbox);
			global::Gtk.Box.BoxChild w1 = ((global::Gtk.Box.BoxChild)(this.outerBox [this.vbox]));
			w1.Position = 0;
			this.alignment2.Add (this.outerBox);
			this.Add (this.alignment2);
			if ((this.Child != null)) {
				this.Child.ShowAll ();
			}
			this.Hide ();
		}
	}
}
