
// This file has been generated by the GUI designer. Do not modify.
namespace Revanche.Views.Fields
{
	public partial class Text
	{
		private global::Gtk.Frame frame1;
		private global::Gtk.Alignment alignment1;
		private global::Gtk.TextView textview1;

		protected virtual void Build ()
		{
			global::Stetic.Gui.Initialize (this);
			// Widget Revanche.Views.Fields.Text
			global::Stetic.BinContainer.Attach (this);
			this.Name = "Revanche.Views.Fields.Text";
			// Container child Revanche.Views.Fields.Text.Gtk.Container+ContainerChild
			this.frame1 = new global::Gtk.Frame ();
			this.frame1.Name = "frame1";
			// Container child frame1.Gtk.Container+ContainerChild
			this.alignment1 = new global::Gtk.Alignment (0F, 0F, 1F, 1F);
			this.alignment1.Name = "alignment1";
			// Container child alignment1.Gtk.Container+ContainerChild
			this.textview1 = new global::Gtk.TextView ();
			this.textview1.CanFocus = true;
			this.textview1.Name = "textview1";
			this.textview1.AcceptsTab = false;
			this.textview1.WrapMode = ((global::Gtk.WrapMode)(2));
			this.alignment1.Add (this.textview1);
			this.frame1.Add (this.alignment1);
			this.Add (this.frame1);
			if ((this.Child != null)) {
				this.Child.ShowAll ();
			}
			this.Hide ();
			this.textview1.KeyPressEvent += new global::Gtk.KeyPressEventHandler (this.handlerKey);
		}
	}
}
