
// This file has been generated by the GUI designer. Do not modify.
namespace Revanche.Views.Objects
{
	public partial class Children
	{
		private global::Gtk.Alignment alignment1;
		private global::Gtk.VBox vbox;

		protected virtual void Build ()
		{
			global::Stetic.Gui.Initialize (this);
			// Widget Revanche.Views.Objects.Children
			global::Stetic.BinContainer.Attach (this);
			this.Name = "Revanche.Views.Objects.Children";
			// Container child Revanche.Views.Objects.Children.Gtk.Container+ContainerChild
			this.alignment1 = new global::Gtk.Alignment (0.5F, 0.5F, 1F, 1F);
			this.alignment1.Name = "alignment1";
			this.alignment1.LeftPadding = ((uint)(10));
			this.alignment1.TopPadding = ((uint)(10));
			// Container child alignment1.Gtk.Container+ContainerChild
			this.vbox = new global::Gtk.VBox ();
			this.vbox.Name = "vbox";
			this.alignment1.Add (this.vbox);
			this.Add (this.alignment1);
			if ((this.Child != null)) {
				this.Child.ShowAll ();
			}
			this.Hide ();
		}
	}
}
